{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.novemdecillion.utils",
    "module": "novemdecillion-utils-spring-boot",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h7fk362hibhx7dusofspugz72y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "novemdecillion-utils-spring-boot-1.0.0.jar",
          "url": "novemdecillion-utils-spring-boot-1.0.0.jar",
          "size": 2715,
          "sha512": "eb3e490f564769cd16422c4bed7c24dd8cdf916907bc9e5f6f56d54dc7d0bd20927caa75f8a7d5db38ef4b3eb1fc1bf6d99bd8423e7b5c87515171f5702781ee",
          "sha256": "a559509519c57057110417d02d44c21a044211704e604d82b719f09a979385bb",
          "sha1": "4a0d0248262fdd43116bc91764b997b8c4ffdfee",
          "md5": "bf34057ec5222560192f9655db9a0aae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "novemdecillion-utils-spring-boot-1.0.0.jar",
          "url": "novemdecillion-utils-spring-boot-1.0.0.jar",
          "size": 2715,
          "sha512": "eb3e490f564769cd16422c4bed7c24dd8cdf916907bc9e5f6f56d54dc7d0bd20927caa75f8a7d5db38ef4b3eb1fc1bf6d99bd8423e7b5c87515171f5702781ee",
          "sha256": "a559509519c57057110417d02d44c21a044211704e604d82b719f09a979385bb",
          "sha1": "4a0d0248262fdd43116bc91764b997b8c4ffdfee",
          "md5": "bf34057ec5222560192f9655db9a0aae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "novemdecillion-utils-spring-boot-1.0.0-sources.jar",
          "url": "novemdecillion-utils-spring-boot-1.0.0-sources.jar",
          "size": 1496,
          "sha512": "6030049b9c393fa9c4b90e2cdb97a6b844875b7e29f92cc194b05e37a8b12f1fcc76f9cd3c966944f807ebd178c566ac105c6314396150765d8928c860be4b9b",
          "sha256": "5c9d8391e85bfec601b837fa2d8ad60c6b0021d1542f339a423e24cbe3e3b392",
          "sha1": "b27880c22543f4f66ac9a06016b78d8ec93d36a6",
          "md5": "ab7553abc198ee106710635562ea2cf5"
        }
      ]
    }
  ]
}
